bahrmichael/factorio-tycoon

- changelog.txt
- control.lua
- locale/en/localization.cfg
- tycoon-story.lua
closes https://github.com/bahrmichael/factorio-tycoon/issues/20
> feat: support multiple cities and extend story

- changelog.txt
- control.lua
- tycoon-story.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/21
> feat: randomly place primary industries

- locale/pt-BR/localization.cfg
all items, entities, recipes, research were translated into Brazilian Portuguese
> brazilian tranbslation

- changelog.txt
- control.lua
> feat: include primary production name in tag

- changelog.txt
- control.lua
- locale/en/localization.cfg
- tycoon-story.lua
> feat: extended story and better town hall gui

- changelog.txt
- control.lua
- locale/en/localization.cfg
- tycoon-story.lua
See https://mods.factorio.com/mod/tycoon/discussion/6519a3b81330d4a2300d9b30
> fix: destroying buildings doesn't crash the game anymore

- changelog.txt
- city.lua
- control.lua
- prototypes/entities/excavation-pit.lua
- prototypes/entities/town-hall.lua
- tycoon-story.lua
For https://github.com/bahrmichael/factorio-tycoon/issues/45
Closes https://github.com/bahrmichael/factorio-tycoon/issues/44
> fix: prevent town hall destruction / handling of water tower removal

- changelog.txt
- control.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/63
> chore: update prices per unit of resource consumed

- changelog.txt
- control.lua
- locale/en/localization.cfg
Closes https://github.com/bahrmichael/factorio-tycoon/issues/55
> feat: spawn fisheries

- consumption.lua
- control.lua
- prototypes/recipes/buildings.lua
- prototypes/recipes/butchery.lua
- prototypes/recipes/husbandry.lua
- prototypes/recipes/processing.lua
Fixes: https://github.com/bahrmichael/factorio-tycoon/issues/97
> fix: recipes should not be enabled by default + other small fixes

- control.lua
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/93
> fix: let the town build an early treasury

- prototypes/technologies/tech.lua
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/100
> fix: align tech tree with demands

- city.lua
- consumption.lua
- control.lua
- prototypes/entities/excavation-pit.lua
- prototypes/entities/houses-highrise.lua
- prototypes/entities/houses-residential.lua
- prototypes/entities/houses-simple.lua
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/89
Also fixes an issue where houses can't upgrade if any tier is not supplied.
Allows special buildings to always complete construction if any housing tier is supplied.
> fix: house locations are off

- prototypes/entities/apple-farm.lua
- prototypes/entities/stable.lua
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/88
> fix: align apple pipe input

- control.lua
- locale/en/localization.cfg
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/102
> feat: add water tower warning

- control.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/85
> feat: spawn an apple farm close to the town hall

- control.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/94
> feat: improve fishery spawn places

- changelog.txt
- consumption.lua
- prototypes/recipes/university-science.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/96
> feat: increase currency value

- changelog.txt
- control.lua
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/110
> fix: don't let primary industries spawn right next to water or cliffs

- changelog.txt
- city.lua
- consumption.lua
- control.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/70
> chore: predictable randomizer

- changelog.txt
- city.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/98
> feat: let roads build below power poles, ground pipes, and lamps

- changelog.txt
- control.lua
- locale/en/localization.cfg
- prototypes/technologies/tech.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/84
Closes https://github.com/bahrmichael/factorio-tycoon/issues/79
> feat: rework upgrade gui to construction gui

- control.lua
- locale/en/localization.cfg
- prototypes/recipes/processing.lua
- prototypes/technologies/tech.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/86
> feat: call out missing supply buildings

- README.md
- control.lua
- locale/en/localization.cfg
Closes https://github.com/bahrmichael/factorio-tycoon/issues/81
> feat: add intro messages

- control.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/80
> feat: rebalance construction material

- changelog.txt
- consumption.lua
- control.lua
- prototypes/recipes/processing.lua
- prototypes/technologies/tech.lua
Some fixes and changelog update.
Closes https://github.com/bahrmichael/factorio-tycoon/issues/125
Closes https://github.com/bahrmichael/factorio-tycoon/issues/124
> feat: release major rework 0.0.20

- changelog.txt
- prototypes/entities/apple-farm.lua
- prototypes/entities/butchery.lua
- prototypes/entities/excavation-pit.lua
- prototypes/entities/fishery.lua
- prototypes/entities/houses-highrise.lua
- prototypes/entities/houses-residential.lua
- prototypes/entities/houses-simple.lua
- prototypes/entities/town-hall.lua
- prototypes/entities/treasury.lua
- prototypes/entities/wheat-farm.lua
Turns out I forgot to add the rotatable=false flag to the butchery.
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/41
> fix: make some entities not rotatable

- changelog.txt
- city.lua
- control.lua
- locale/en/localization.cfg
Closes https://github.com/bahrmichael/factorio-tycoon/issues/127
> chore: harden code for grid access

- changelog.txt
- city.lua
- control.lua
- prototypes/entities/excavation-pit.lua
- prototypes/entities/houses-highrise.lua
- prototypes/entities/houses-residential.lua
- prototypes/entities/houses-simple.lua
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/128
> fix: house placements, warning message

- changelog.txt
- city.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/99
> feat: rail crossings

- changelog.txt
- city.lua
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/9
> fix: don't expand into uncharted areas

- changelog.txt
- prototypes/recipes/husbandry.lua
2% for cows to vanish while producing milk.
> chore: dying cows

- changelog.txt
- city.lua
- control.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/137
> feat: rediscover unused fields

- city.lua
- control.lua
Fix https://github.com/bahrmichael/factorio-tycoon/issues/149
> fix: buildings shouldn't upgrade if the tech is not researched

- changelog.txt
- control.lua
- locale/en/localization.cfg
Closes https://github.com/bahrmichael/factorio-tycoon/issues/130
> chore: mention urbanization

- city.lua
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/157
> fix: don't place gardens next to roads

- city.lua
- control.lua
- prototypes/entities/apple-farm.lua
- prototypes/entities/butchery.lua
- prototypes/entities/excavation-pit.lua
- prototypes/entities/fishery.lua
- prototypes/entities/hardware-store.lua
- prototypes/entities/market.lua
- prototypes/entities/stable.lua
- prototypes/entities/town-hall.lua
- prototypes/entities/treasury.lua
- prototypes/entities/wheat-farm.lua
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/167
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/168
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/169
> chore: some fixes

- city.lua
- constants.lua
- consumption.lua
- control.lua
- segments.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/153
> chore: add constants file

- changelog.txt
- control.lua
- migrations/0.1.1-recipe-lock.lua
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/172
> fix: prevent player from changing primary industry recipes

- changelog.txt
- prototypes/entities/hardware-store.lua
- prototypes/entities/market.lua
- prototypes/entities/treasury.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/144
> feat: buildings network connectivity

- prototypes/entities/university.lua
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/197
> fix: universities shouldn't rotate

- changelog.txt
- consumption.lua
Fixes https://github.com/bahrmichael/factorio-tycoon/issues/177
> fix: show supplied when nothing's required yet

- .github/workflows/patch-crowdin-format.yaml
- locale/en/mod-setting-description.cfg
- locale/en/mod-setting-name.cfg
- migrations/0.4.1-fix-primary-industries-array.lua
- primary-industries.lua
- prototypes/recipes/growing.lua
- research-event-handler.lua
- settings.lua
Hi! First of all, Thanks for the cool mod!
I've ran into some issues, so there are some fixes... _hoping commit messages are informative enough to review changes_
Looking forward to contribute for the **Tycoon** mod!
/off
I'm currently playing with x1000 science cost, building blocks of 1800 SPM (full red belt) and v0.4.0 update few days ago got me way more currency for my ~4k city, so now i get ~330/min of blue packs consuming around 7-9k currency/min. Not that easy to get from Treasury, though - it's almost 4 red belts (4*1800). Waiting for university productivity update here... :)
I didn't touch fishery productivity curve: no research yet, not knowing your target numbers (same 1800/min @ 10 level?) for meat.
Don't know the license yet, but i'd accept any license for such small fixes
-- …
> fix productivity research and industry recipe mangling + tag text anti-clutter option

- locale/en/mod-setting-description.cfg
- locale/en/mod-setting-name.cfg
This PR updates the names and description of settings to make the outcome easier to understand for players.
@winex could you review this and check if it's still accurate? Thanks :)
> chore: rename settings for players

- city-planner.lua
- city.lua
- construction-event-handler.lua
moved these few commits from old `winex:fix-desync` #288, which isn't going to be merged soon or ever...
> chore: few forgotten fixes

- chunk-charted-handler.lua
- city-planner.lua
- city.lua
- construction-event-handler.lua
- consumption.lua
- gui.lua
- migrations/0.5.0-add-city-surface-index.lua
- passengers.lua
- player-event-handler.lua
- primary-industries.lua
- remote_interfaces.md
- tags-queue.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/297
This PR updates the code so that it can work with multiple surfaces.
Urban planning centers (to be removed soon) only work with the starting surface, and towns only spawn on the starting surface.
> feat: multi surface support

- city-planner.lua
- city.lua
- constants.lua
- control.lua
- floor-upgrades-queue.lua
- util.lua
Closes https://github.com/bahrmichael/factorio-tycoon/issues/298
> feat: different floor types

- constants.lua
- construction-event-handler.lua
- player-event-handler.lua
- primary-industries.lua
- util.lua
don't squash, please. best to be merged after #307 is in
_this is picked from destroy event fix #300, which depends on it_
> chore: simplify construction event handlers + few functions

- .github/workflows/patch-crowdin-format.yaml
- .github/workflows/publish.yaml
https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
> remove compromised library
